# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required

# https://releases.ubuntu.com/ use the latest LTS release of ubuntu
dist: bionic
language: scala
scala:
  - 2.12.14
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install:
  - ./build/mvn --version

script:
  - ./build/mvn clean install -Dmaven.javadoc.skip=true -V

after_success:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"

after_failure:
  - echo "Travis exited with ${TRAVIS_TEST_RESULT}"
  - for log in `find * -name "kyuubi-spark-sql-engine.log*"`; do echo "=========$log========="; grep "ERROR" $log -A 100 -B 20; done
  - for log in `find * -name "unit-tests.log"`;  do echo "=========$log========="; grep "ERROR" $log -A 100 -B 20; done
