#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Kyuubi Doc Improvement Report
title: "[DOCS] "
description: Problems and issues with docs of Apache Kyuubi
labels: ["kind:bug", "kind:documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for finding the time to report the problem! We really appreciate the community efforts to improve Kyuubi.
        
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: The Code of Conduct helps create a safe space for everyone. We require that everyone agrees to it.
      options:
        - label: >
            I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)
          required: true
          
  - type: checkboxes
    attributes:
      label: Search before asking
      options:
        - label: >
            I have searched in the [issues](https://github.com/apache/incubator-kyuubi/issues?q=is%3Aissue) and found no similar
            issues.
          required: true
          
  - type: textarea
    attributes:
      label: What do you see as an issue?
      description: Please describe the issue with documentation you have.
      placeholder: >
        Please include links to the documentation that has the problem and possibly screenshots showing
        the problem. Explain why do you think it is an issue. Make sure you include view of the target
        audience of the documentation. Please explain why you think the docs are wrong.
        
  - type: textarea
    attributes:
      label: Solving the problem
      description: How do you think the problem can be solved?
      placeholder: >
        Please explain how you think the documentation could be fixed. Ideally specify where a new or missing
        documentation should be added and what kind of information should be included. Sometimes people
        writing the documentation do not realise that some assumptions the have might not be in the heads
        of the reader, so try to explain exactly what you would like to see in the docs and why.
        
  - type: textarea
    attributes:
      label: Anything else
      description: Anything else we need to know?
      placeholder: >
        How often does this problem occur? (Once? Every time? Only when certain conditions are met?)
        Any relevant logs to include? Put them here inside fenced
        ``` ``` blocks or inside a foldable details tag if it's long:
        <details><summary>x.log</summary> lots of stuff </details>
        
  - type: checkboxes
    attributes:
      label: Are you willing to submit PR?
      description: >
        A pull request is optional, but we are glad to help you in the contribution process
        especially if you already know a good understanding of how to implement the fix.
        Kyuubi is a community-driven project and we love to bring new contributors in.
      options:
        - label: Yes I am willing to submit a PR!

  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this Doc improvement report!"
