name: Publish Docker image

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    concurrency:
      # this group should be global unique
      group: push-docker-image
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Kyuubi Docker Image
        run: docker build --tag apache/kyuubi:master-snapshot --file docker/Dockerfile .
      - name: Docker image
        run: docker images
      - name: Push Docker image
        run: docker push apache/kyuubi:master-snapshot
