name: Publish Docker image

on:
  push:
    branches:
      - master
      - docker-dev

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    concurrency:
      # this group should be global unique
      group: push-docker-image
      cancel-in-progress: true
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          file: docker/Dockerfile
          push: true
          tags: apache/kyuubi:latest
