name: Publish Snapshot

on:
  schedule:
  - cron: '0 0 * * *'

jobs:
  publish-snapshot:
    if: ${{ startsWith(github.repository, 'apache/') }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - branch-1.3
    steps:
    - name: Checkout repository
      uses: actions/checkout@master
      with:
        ref: ${{ matrix.branch }}
    - name: Cache Maven local repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: snapshot-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          snapshot-maven-
    - name: Install Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Publish snapshot
      env:
        ASF_USERNAME: ${{ secrets.NEXUS_USER }}
        ASF_PASSWORD: ${{ secrets.NEXUS_PW }}
      run: |
        rm -rf ~/.m2/repository/org/apache/kyuubi
        ./build/mvn clean deploy -DskipTests -Pspark-provided -s ./build/release/asf-settings.xml
