name: Web UI

on:
  push:
    branches:
      - master
      - branch-*
  pull_request:
    branches:
      - master
      - branch-*

concurrency:
  group: web-ui-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-ui:
    name: Kyuubi Web UI check
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      # from https://github.com/marketplace/actions/setup-node-js-environment
      - name: setup npm
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: npm run coverage & build
        run: |
          npm run coverage
          npm run build
